version: "3.9"

services:

  app:

    build: .

    container_name: laundry-app

    restart: unless-stopped

    ports:
      - "3000:3000"

    environment:
      NODE_ENV: production
      MONGO_URI: mongodb://172.17.0.1:27017/laundry
      SESSION_SECRET: laundry-secret